"""
In this script, we will run simulations varying the size the
metagenome. We will run 100 simulations for each size. 
We will vary the size of the metagenome: 0.1, 0.2, 0.4, 0.8, 1.6, 3.2, 6.4, 12.8, 25.6, 51.2, 102.4
We will use 64 genomes. Other parameters will be default.
"""

# command to run simulation:
# python ../../run_camisim.py 64 --seed xx --size <size>
#--config config_size_seed_xx.ini
#--outdir out_size_seed_xx
#--gene_g_t gene_ground_truth_size_seed_xx
#--ko_g_t ko_ground_truth_size_seed_xx
#--metagenome_filename metagenome_size_seed_xx.fastq
#--genome_cov_file genome_coverages_size_seed_xx

num_simulations = 100

def main():
    shell_script_name = "run_simulations_varying_size_of_metagenomes.sh"
    shell_script = open(shell_script_name, "w")
    shell_script.write("#!/bin/bash\n\n")
    shell_script.write("# This script was automatically generated by the script ")
    shell_script.write("run_simulations_varying_size_of_metagenomes.py\n\n")

    counter = 0
    for size in [0.1, 0.2, 0.4, 0.8, 1.6, 3.2, 6.4, 12.8, 25.6, 51.2, 102.4]:
        for i in range(num_simulations):
            seed = i + 1
            shell_script.write("python ../../run_camisim.py ")
            shell_script.write("64 ")
            shell_script.write("--seed " + str(seed) + " ")
            shell_script.write("--size " + str(size) + " ")
            shell_script.write("--config config_" + str(size) + "_seed_" + str(seed) + ".ini ")
            shell_script.write("--outdir out_" + str(size) + "_seed_" + str(seed) + " ")
            shell_script.write("--gene_g_t gene_ground_truth_" + str(size) + "_seed_" + str(seed) + " ")
            shell_script.write("--ko_g_t ko_ground_truth_" + str(size) + "_seed_" + str(seed) + " ")
            shell_script.write("--metagenome_filename metagenome_" + str(size) + "_seed_" + str(seed) + ".fastq ")
            shell_script.write("--genome_cov_file genome_coverages_" + str(size) + "_seed_" + str(seed) + " &\n")

            counter += 1
            if counter % 32 == 0:
                shell_script.write("wait\n\n")

    shell_script.close()