
"""
In this script, we will run simulations varying the number of genomes in the
metagenome. We will run 100 simulations for each number of genomes in the
metagenome. We will vary the number of genomes in the metagenome from 1 to 1024
in powers of 2. Other parameters will be default.
"""

# command to run simulation:
# python ../../run_camisim.py <num_genomes> --seed xx --size 0.1 
#--config config_num_genomes_seed_xx.ini 
#--outdir out_num_genomes_seed_xx 
#--gene_g_t gene_ground_truth_num_genomes_seed_xx
#--ko_g_t ko_ground_truth_num_genomes_seed_xx 
#--metagenome_filename metagenome_num_genomes_seed_xx.fastq 
#--genome_cov_file genome_coverages_num_genomes_seed_xx

num_simulations = 50

def main():
    shell_script_name = "run_simulations_varying_num_genomes.sh"
    shell_script = open(shell_script_name, "w")
    shell_script.write("#!/bin/bash\n\n")
    shell_script.write("# This script was automatically generated by the script ")
    shell_script.write("run_simulations_varying_num_genomes.py\n\n")

    counter = 0
    for num_genomes in [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]:
        for i in range(num_simulations):
            seed = i + 1
            shell_script.write("python ../../run_camisim.py ")
            shell_script.write(str(num_genomes) + " ")
            shell_script.write("--seed " + str(seed) + " ")
            shell_script.write("--size 0.1 ")
            shell_script.write("--config config_" + str(num_genomes) + "_seed_" + str(seed) + ".ini ")
            shell_script.write("--outdir out_" + str(num_genomes) + "_seed_" + str(seed) + " ")
            shell_script.write("--gene_g_t gene_ground_truth_" + str(num_genomes) + "_seed_" + str(seed) + " ")
            shell_script.write("--ko_g_t ko_ground_truth_" + str(num_genomes) + "_seed_" + str(seed) + " ")
            shell_script.write("--metagenome_filename metagenome_" + str(num_genomes) + "_seed_" + str(seed) + ".fastq ")
            shell_script.write("--genome_cov_file genome_coverages_" + str(num_genomes) + "_seed_" + str(seed) + " &\n")

            counter += 1
            if counter % 32 == 0:
                shell_script.write("wait\n\n")

    shell_script.close()

if __name__:
    main()